# Generated by Django 4.0.4 on 2022-04-27 16:13

import autoslug.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(validators=[django.core.validators.MinLengthValidator(20), django.core.validators.MaxLengthValidator(100)], verbose_name='Adres Bilgisi')),
                ('email', models.EmailField(max_length=30, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format '05325165796'. Up to 11 digits allowed.", regex='^\\+?1?\\d{10,11}$')], verbose_name='Telefon')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'İletişim',
                'db_table': 'tblcontact',
            },
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ülke Adı')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'Ülkeler',
                'db_table': 'tblcountry',
            },
        ),
        migrations.CreateModel(
            name='genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Film Türü')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'Türler',
                'db_table': 'tblgenre',
            },
        ),
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Dil')),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'Diller',
                'db_table': 'tbllanguage',
            },
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Film Adı')),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Film Hakkında')),
                ('image', models.ImageField(upload_to='movies', verbose_name='Film Resmi')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('movie_time', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(35), django.core.validators.MaxValueValidator(300)], verbose_name='Film Süresi')),
                ('age_limit', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(99)], verbose_name='Yaş Sınırı')),
                ('movie_budget', models.DecimalField(decimal_places=3, max_digits=7, verbose_name="Film'in Bütçesi")),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.country', verbose_name="Film'in Vizyona Girdiği Ülke")),
                ('genre', models.ManyToManyField(to='movieapp.genre', verbose_name='Film Türü')),
                ('language', models.ManyToManyField(to='movieapp.language', verbose_name="Film'in Dili")),
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'Filmler',
                'db_table': 'tblmovie',
            },
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Video Başlığı')),
                ('url', models.CharField(max_length=200, verbose_name='Video URL Adresi')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmURL', to='movieapp.movie', verbose_name='Film ID')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'Videolar',
                'db_table': 'tblvideo',
            },
        ),
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Fotoğraf Başlığı')),
                ('photo', models.ImageField(blank='False', upload_to='inmoviesPhoto', verbose_name='Fotoğraflar')),
                ('moviephoto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.movie', verbose_name='Filme ait Fotoğraflar')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'fotograflar',
                'db_table': 'tblphoto',
            },
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSurname', models.CharField(max_length=60, validators=[django.core.validators.RegexValidator('^[a-z\\sA-Z]*$', 'Sadece Alfabetik karakter girişi yapabilirsiniz!')], verbose_name='Ad ve Soyad')),
                ('image', models.ImageField(upload_to='person', verbose_name='Resim')),
                ('birthday', models.DateField(verbose_name='Doğum Tarihi')),
                ('gender', models.CharField(choices=[('M', 'Erkek'), ('F', 'Kadın')], max_length=1, verbose_name='Cinsiyet')),
                ('duty_type', models.CharField(choices=[('1', 'Görevli'), ('2', 'Oyuncu'), ('3', 'Yönetmen'), ('4', 'Senarist')], max_length=1, verbose_name='Görev Türü')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='nameSurname', unique=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movieapp.contact', verbose_name='Adres')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'Personeller',
                'db_table': 'tblperson',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='people',
            field=models.ManyToManyField(related_name='ekipFilm', to='movieapp.person', verbose_name="Film'in Yetkilileri"),
        ),
    ]
