# Generated by Django 4.0.4 on 2022-04-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='nameSurname',
            field=models.CharField(max_length=60, verbose_name='Ad ve Soyad'),
        ),
    ]
