# Generated by Django 4.0.4 on 2022-04-29 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_alter_person_namesurname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movieCountry', to='movieapp.country', verbose_name="Film'in Vizyona Girdiği Ülke"),
        ),
    ]
