# Generated by Django 4.0.4 on 2022-04-29 04:58

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_alter_movie_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='nameSurname',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(re.compile('[^\\W\\d_]+$'), 'Only alphabetic')], verbose_name='Ad ve Soyad'),
        ),
    ]
