# Generated by Django 4.0.4 on 2022-04-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0006_series_movie_serie'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='series',
            table='tblserie',
        ),
    ]
