# Generated by Django 4.0.4 on 2022-04-30 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0007_alter_series_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='moviephoto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.movie', verbose_name='Film ID'),
        ),
    ]
