# Generated by Django 4.0.4 on 2022-04-30 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0008_alter_photo_moviephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='serie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seriesMovie', to='movieapp.series'),
        ),
    ]
