# Generated by Django 4.0.4 on 2022-05-03 02:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0013_alter_comment_mesaj_alter_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='mesaj',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Yapılan Yorum'),
        ),
    ]
