# Generated by Django 4.0.4 on 2022-05-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0014_alter_comment_mesaj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yorum Yapılan Tarih'),
        ),
    ]
