# Generated by Django 4.0.4 on 2022-05-03 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0015_alter_comment_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comment',
            new_name='commentX',
        ),
    ]
