# Generated by Django 4.0.4 on 2022-05-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0016_rename_comment_commentx'),
    ]

    operations = [
        migrations.CreateModel(
            name='deneme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='denemeTitle')),
            ],
        ),
    ]
