# Generated by Django 4.0.4 on 2022-05-03 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0017_deneme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='deneme',
        ),
    ]
