# Generated by Django 4.0.4 on 2022-05-09 14:13

import autoslug.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0018_delete_deneme'),
    ]

    operations = [
        migrations.CreateModel(
            name='serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Dizi Adı')),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Dizi Hakkında')),
                ('image', models.ImageField(upload_to='serial', verbose_name='Dizi Resmi')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('age_limit', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(99)], verbose_name='Yaş Sınırı')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serialCountry', to='movieapp.country', verbose_name="Dizi'nin Çekildiği Ülke")),
                ('genre', models.ManyToManyField(related_name='serialCategory', to='movieapp.genre', verbose_name='Dizi Türü')),
                ('language', models.ManyToManyField(to='movieapp.language', verbose_name="Dizi'nin Dili")),
                ('people', models.ManyToManyField(related_name='ekipDizi', to='movieapp.person', verbose_name="Dizi'nin Yetkilileri")),
            ],
            options={
                'verbose_name': 'serial',
                'verbose_name_plural': 'Diziler',
                'db_table': 'tblserial',
            },
        ),
    ]
