# Generated by Django 4.0.4 on 2022-05-09 14:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0019_serial'),
    ]

    operations = [
        migrations.CreateModel(
            name='episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, verbose_name='Video URL Adresi')),
                ('episode_time', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(35), django.core.validators.MaxValueValidator(300)], verbose_name='Bölüm Süresi')),
                ('budget', models.DecimalField(decimal_places=3, max_digits=6, verbose_name="Bölüm'ün Bütçesi")),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serialEpisode', to='movieapp.serial')),
            ],
            options={
                'verbose_name': 'episode',
                'verbose_name_plural': 'Diziler',
                'db_table': 'tblEpisode',
            },
        ),
    ]
