# Generated by Django 4.0.4 on 2022-05-09 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0020_episode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'verbose_name': 'episode', 'verbose_name_plural': 'Bölümler'},
        ),
        migrations.AddField(
            model_name='commentx',
            name='serialID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='serialComment', to='movieapp.serial'),
            preserve_default=False,
        ),
    ]
