# Generated by Django 4.0.4 on 2022-05-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0021_alter_episode_options_commentx_serialid'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Bölüm Adı'),
            preserve_default=False,
        ),
    ]
