# Generated by Django 4.0.4 on 2022-05-09 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0022_episode_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='budget',
        ),
    ]
