# Generated by Django 4.0.4 on 2022-05-09 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0023_remove_episode_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='serialVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Video Başlığı')),
                ('url', models.CharField(max_length=200, verbose_name='Video URL Adresi')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diziURL', to='movieapp.serial', verbose_name='Dizi ID')),
            ],
            options={
                'verbose_name': 'diziVideo',
                'verbose_name_plural': 'Dizi Videolar',
                'db_table': 'tblserialVideo',
            },
        ),
    ]
