# Generated by Django 4.0.4 on 2022-05-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0025_rename_movie_serialvideo_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Yayınlanma Tarihi'),
        ),
    ]
