# Generated by Django 4.0.4 on 2022-05-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0026_episode_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_quality',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Görüntü Kalitesi'),
        ),
    ]
