# Generated by Django 4.0.4 on 2022-05-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0027_movie_image_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image_quality',
        ),
    ]
