# Generated by Django 4.0.4 on 2022-05-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0029_movie_image_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image_quality',
            field=models.IntegerField(blank=True, choices=[('1', '4K'), ('2', '1080P'), ('3', '720P'), ('4', '480P')], null=True, verbose_name='Görüntü Kalitesi'),
        ),
    ]
