# Generated by Django 4.0.4 on 2022-05-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0030_alter_movie_image_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image_quality',
            field=models.IntegerField(choices=[('1', '4K'), ('2', '1080P'), ('3', '720P'), ('4', '480P')], verbose_name='Görüntü Kalitesi'),
        ),
    ]
